- processor/src/services/adyen-payment.service.ts
An error was happening in the payment connectors when trying to create a payment and the cart was anonymous and later the customer signed-in or signed-up so, in summary, the cart contains 2 references, one to a customer id and one to an anonymous id.
Following exception caused the issue: 
```
{
"statusCode": 400,
"message": "The anonymousId 'idString' was already used for sign-in or sign-up.",
"errors": [
{
"code": "InvalidOperation",
"message": "The anonymousId 'idString' was already used for sign-in or sign-up."
}
]
}
```
The issue has been solved by assigning only one customer reference to the payment, either the customer id or the anonymous id, having preference the customer id over the anonymous id.
More details in: https://commercetools.atlassian.net/browse/SCC-2292
> fix(payments): solved issue when creating a payment from a cart that contains both a customer id and an anonymous id

- enabler/src/components/payment-methods/applepay.ts
- enabler/src/components/payment-methods/googlepay.ts
- enabler/src/components/payment-methods/paypal.ts
- enabler/src/payment-enabler/payment-enabler.ts
It looks like `onClick` has a different signature on both methods:
For Googlepay it receives `resolve` and `reject` as the first and second param
For Paypal the second param is an object containing `resolve` and `reject`
> Support terms and conditions error on paypal and googlepay methods

- enabler/src/components/base.ts
- enabler/src/components/payment-methods/applepay.ts
- enabler/src/payment-enabler/payment-enabler.ts
See Jira: https://commercetools.atlassian.net/browse/SCC-2362
This PR exposes the `isAvailable` method for Adyen so we can control when payment methods should and should not be rendered in the checkout. It uses Adyen's isAvailable helper.
Edit: 
see below, Apple Pay is rendered in Safari but not in Chrome
| Safari | Chrome |
|--------|--------|
| ![image](https://github.com/commercetools/connect-payment-integration-adyen/assets/17336834/6f8b6fb4-4350-46e6-8271-86ca246c7f9b) | ![image (1)](https://github.com/commercetools/connect-payment-integration-adyen/assets/17336834/c6cc2685-cfaf-4544-9509-e6cc6375e0d7) |
> feat(adyen): expose isAvailable

- enabler/src/components/payment-methods/klarna-pay-later.ts
- enabler/src/components/payment-methods/klarna-pay-now.ts
- enabler/src/components/payment-methods/klarna-pay-over-time.ts
1. [SCC-2251](https://commercetools.atlassian.net/browse/SCC-2251)
2. [SCC-2252](https://commercetools.atlassian.net/browse/SCC-2252)
3. [SCC-2253](https://commercetools.atlassian.net/browse/SCC-2253)
As a followup on https://github.com/commercetools/connect-payment-integration-adyen/pull/129 for Klarna the componentHasSubmit needs to have the value of `true` (which is the default value).
> feat(klarna): remove the componentHasSubmit for all Klarna options

- processor/package-lock.json
- processor/package.json
- processor/src/server/app.ts
- processor/src/services/abstract-payment.service.ts
- processor/src/services/adyen-payment.service.ts
- processor/src/services/converters/capture-payment.converter.ts
- processor/src/services/converters/helper.converter.ts
- processor/test/routes.test/operations.spec.ts
- processor/test/services/adyen-payment.service.spec.ts
- processor/test/services/converters/capture.converter.spec.ts
- processor/test/utils/mock-order-data.ts
- processor/test/utils/mock-payment-data.ts
**Ticket [SCC-2373](https://commercetools.atlassian.net/browse/SCC-2373)**
**Description**
For certain payment methods, in this case for `klarna` (Pay Later), `klarna_account` (Pay Over Time) and `klarna_paynow` (Pay Now) it requires us to send the line items to Adyen again during a `capture` API call. Same as during the authorisation call. In this PR we extend the `capture` API code to include this.
Sending lineitems to Adyen is conditional. Only if the payment method is (at the time of this PR) one of the three klarna payment methods will we trigger this new logic.
When a payment capture request is coming in we only know the `paymentID` so via this ID we will fetch the CoCo order and as a fallback the cart. If neither could be found an error is returned to the API caller without the …
> feat(processor): send line items to Adyen for capture payments if payment-method requires it

- processor/src/config/payment-method.config.ts
- processor/src/services/adyen-payment.service.ts
- processor/src/services/converters/create-payment.converter.ts
- processor/src/services/converters/notification.converter.ts
- processor/src/services/types/service.type.ts
- processor/test/services/adyen-payment.service.spec.ts
- processor/test/services/converters/notification.converter.spec.ts
Added support for payment methods that do not accept separate captures. 
Those payment methods are auto captured so we are creating the Charge transaction for those cases when Adyen confirms the payment so that we can keep synced the CoCo payment state and the Adyen payment
More details on ticket: https://commercetools.atlassian.net/browse/SCC-2400
> feat(payments): added support for payment methods that do not accept separate captures

- processor/src/dtos/operations/status.dto.ts
- processor/src/services/adyen-payment.service.ts
- processor/test/routes.test/operations.spec.ts
- processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2459
I was making a PR fix to allow the commercetools Checkout mc-app to show the first `message` of any health check with the status `DOWN` however I never saw it returned from the Adyen connector.
After some digging I found out that the the status handler of the [connect-payments-sdk](https://github.com/commercetools/connect-payments-sdk/blob/main/src/api/handlers/status.handler.ts#L34) returns a optional `message` attribute on the root level of any `check` object.
However the Adyen connector health check API definition has it's own DTO model. That DTO model did not have the `message` property defined causing it to be stripped out even if it was defined in the handler itself. This PR fixes it. I have added unit-test to validate that it …
> fix(processor): the health check status endpoint now returns the message attribute

- processor/package-lock.json
- processor/package.json
- processor/src/services/adyen-payment.service.ts
https://commercetools.atlassian.net/browse/SCC-2459
- Bump the `@commercetools/connect-payments-sdk` to `0.8.2` so that it includes https://github.com/commercetools/connect-payments-sdk/pull/109
- Change the Adyen health check error message to include a improved message which is inline with the above changes for the commercetools permissions health check
> chore(processor): improve error message of status handlers

- enabler/dev-utils/session.js
- enabler/index.html
- enabler/src/components/payment-methods/eps.ts
- enabler/src/payment-enabler/adyen-payment-enabler.ts
- enabler/src/payment-enabler/payment-enabler.ts
- processor/src/config/payment-method.config.ts
- processor/src/services/adyen-payment.service.ts
- processor/src/services/converters/payment-components.converter.ts
- processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2403
This PR adds support for the Austrian payment methods `EPS` via Adyen. See the screenshots below of how it looks on the Adyen test environment simulator pages.
-----
> feat(payment): add `EPS` payment method support

- enabler/src/payment-enabler/adyen-payment-enabler.ts
Managed pending responses in the Adyen payment enabler to handle the "Pending" resultCode in addition to the "Authorised" resultCode. We take this status optimistically as a success and set the status to "success" in the component as we do the same in the BE.
> feat(payments): manage pending responses

- enabler/src/dropin/dropin-embedded.ts
fixed PayPal button width to fit in the container.
Before
After
> fix(paypal): fixed paypal button width for drop-in

- processor/package-lock.json
- processor/package.json
- processor/src/services/adyen-payment.service.ts
In order to solve: https://commercetools.atlassian.net/browse/CHECKOUT-171
Accept the notifications which throw errors because the payment can't be found. As this is not a recoverable case, we just accept it so Adyen won't retry the same notification.
When a notification can't be or should not be processed, that's the pattern to follow.
> feat(notifications): accept payment not found notifications

- enabler/vite.config.ts
This connector injects a <style> tag into the document head with the CSS code provided. 
This PR is to include an attribute to the adyen style tag for later cleanup through the SPA after closing:
https://commercetools.atlassian.net/browse/SCC-2721
The attribute will look like this: `<style data-ctc-connector-styles>....</style>`
> feat(chore): Add attribute to adyen style tag for cleanup

- processor/package-lock.json
- processor/package.json
- processor/src/services/converters/helper.converter.ts
Upgrade `connect-payments-sdk` and fix the import path `import { NormalizedShipping } from '@commercetools/connect-payments-sdk`
> feat(cart): exporting common type NormalizedShipping

- processor/src/services/converters/create-payment.converter.ts
- processor/src/services/converters/create-session.converter.ts
The delivery address was not being sent to Adyen when the cart had multi shipping enabled. This PR fixes that and ensures the delivery address is always sent to Adyen if present.
https://commercetools.atlassian.net/browse/SCC-2813
> fix(processor): fix issue sending the delivery address to Adyen 

- processor/package-lock.json
- processor/package.json
- processor/src/dtos/operations/payment-intents.dto.ts
- processor/src/services/abstract-payment.service.ts
- processor/src/services/adyen-payment.service.ts
- processor/src/services/converters/cancel-payment.converter.ts
- processor/src/services/converters/capture-payment.converter.ts
- processor/src/services/converters/notification.converter.ts
- processor/src/services/converters/refund-payment.converter.ts
- processor/src/services/types/operation.type.ts
- processor/src/services/types/service.type.ts
- processor/test/services/adyen-payment.service.spec.ts
- processor/test/services/converters/cancel.converter.spec.ts
- processor/test/services/converters/notification.converter.spec.ts
- processor/test/services/converters/refund.converter.spec.ts
https://commercetools.atlassian.net/browse/SCC-2774
Accept a merchant reference in the payload of the payment intents API. This change allows merchants to set their own payment reference in Adyen for the void, capture and refund.
> feat(payments): accept a merchant reference in payment intents API

- processor/package-lock.json
- processor/package.json
- processor/src/config/payment-method.config.ts
- processor/src/services/converters/helper.converter.ts
- processor/test/services/converters/helper.converter.spec.ts
https://commercetools.atlassian.net/browse/SCC-2901
Previously when I implemented the [fraction digits support in Adyen](https://github.com/commercetools/connect-payment-integration-adyen/pull/288) I made the mistake to re-use the `CurrencyConverters` for the tax rate values as well. Thinking that the logic is the same. However there is one crucial difference. The input for the currency amounts is always integer values but for the tax rate it's possible to have decimal values.
Explicit validations on integers values where added to the `connect-payments-sdk` in `v18` and the package was bumped by [dependabot](https://github.com/commercetools/connect-payment-integration-adyen/pull/308) on 3 of Feb.
This PR uses a new converter function from the …
> fix(processor): fix the tax rate to taxPercentage converter logic to take into account decimal rates

- processor/src/services/converters/notification.converter.ts
- processor/test/services/converters/notification.converter.spec.ts
Added support for "offer closed" events. These events are sent when a payment offer is cancelled and it's the only way to know that payment methods like Przelewy24 were rejected. 
More info on: https://commercetools.atlassian.net/browse/SCC-3000
> feat(payments): added support for "offer_closed" events

- docker-compose.yaml
- enabler/dev-utils/session.js
- enabler/index.html
- enabler/src/components/base.ts
- enabler/src/components/payment-methods/mobilepay.ts
- enabler/src/dropin/dropin-embedded.ts
- enabler/src/payment-enabler/adyen-payment-enabler.ts
- enabler/src/payment-enabler/payment-enabler.ts
- processor/src/services/converters/payment-components.converter.ts
- processor/test/services/adyen-payment.service.spec.ts
**Link to the ticket:** https://commercetools.atlassian.net/browse/SCC-2872
Adds the MobilePay support in the enabler and processor.
Corresponding checkout-anywhere SPA PR https://github.com/checkout-anywhere/checkout-anywhere/pull/7484
Below video shows the MobilePay step using a cart for country `FI` and currency `EUR` for both the `web-component` and `dropin` type. 
Note that doing actual payments is not possible on the Adyen test environment. See [the docs on Adyen](https://docs.adyen.com/payment-methods/mobilepay/web-component/#test-and-go-live).
https://github.com/user-attachments/assets/6b21539f-3076-4aa7-85f2-10bd7e078936
> feat(payments): add support for MobilePay

- processor/README.md
Updates the `processor/README.MD` with the required set of `event` types that need to be enabled in Adyen webhooks for the connector/Checkout to work. The new section can be found under the `## Webhooks` header.
The list of required `event` types is retrieved from [notification.converter.ts](https://github.com/commercetools/connect-payment-integration-adyen/blob/main/processor/src/services/converters/notification.converter.ts#L22) where all incoming notifications go through.
A IDE plugin also reformatted and fixed some issues in the README.MD hence it's a bit larger then just the new section. Compare the [updated](https://github.com/commercetools/connect-payment-integration-adyen/tree/joey-koster-ct/SCC-3051-add-adyen-webhook-in-readme.md/processor) and the …
> chore(processor): update the `README.MD` to indicate all of the required Adyen webhook `event` types

- .gitignore
- enabler/src/payment-enabler/adyen-payment-enabler.ts
- enabler/src/payment-enabler/payment-enabler.ts
https://commercetools.atlassian.net/browse/SCC-3041
Some customer is requesting that we forward the payment reference in failure cases. ATM we're just sending this on success cases, but there's no reason for not sending it on failure cases if available, so we're adding this as a reference
> feat(payments): Add paymentReference to onSuccess and onError callbacks

- processor/README.md
Documented the notifications endpoint and how to configure notifications in Adyen.
This is needed to enable the support team to direct customers to these docs when they have questions about setting up notifications in Adyen.
> feat(docs): added notifications details

- enabler/package-lock.json
- enabler/package.json
we are having problems loading Apple Pay and we think the issue could be related to the recent upgrade of the adyen-web package.
https://commercetools.atlassian.net/browse/SCC-3107?atlOrigin=eyJpIjoiNDk4YjkyNDQ0YTQyNGUyMjk5ZTM4NDA2ZTdkMjMzZDciLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> chore(dependencies): revert adyen-web upgrade

- enabler/src/converters/locale.converter.ts
- enabler/src/payment-enabler/adyen-payment-enabler.ts
- processor/package-lock.json
- processor/package.json
https://commercetools.atlassian.net/browse/SCC-2860
converted the locale received by the enabler to an Adyen supported locale. It defaults to en-US.
This avoids getting CORS errors in the console if the locale does not match a supported locale.
> feat(payments): converted locale to Adyen's supported locales

- enabler/dev-utils/session.js
- enabler/index.html
Rename it into OAuth Token and JSON Web Token to avoid ambiguity
> chore(enabler): rename access token variable to avoid ambiguity

- enabler/index.html
This is in continuation to the [last PR](https://github.com/commercetools/connect-payment-integration-adyen/pull/402) on making connector methods asynchronous. This one enables the async await usage in index.html for testing purposes.
> - added async mounts and submits to index.html for tests

- processor/src/services/converters/notification.converter.ts
- processor/test/services/converters/notification.converter.spec.ts
https://commercetools.atlassian.net/browse/SCC-3469
Fixed issue processing capture failed notifications. There was a trailing space that prevented to process properly those notifications.
> fix(notifications): Fix issue that caused failed capture not to be processed

- enabler/package-lock.json
- enabler/package.json
`esbuild` version `0.24.0` has a vulnerability. In the enabler this version was explicitly installed using the `overrides` part of the `package.json`. A `npm audit` will result in this vulnerability being reported.
I removed the `esbuild` from the `overrides` and now the installed version is:
with `npm audit` reporting no more vulnerabilities.
I did some local testing and everything seems good.
> fix(enabler): remove override from package.json for esbuild version
