.github/workflows/ci.yml
- Add `npm run build` command into CI pipeline for both `enabler` and `processor`
=> fix(all): add typescript compilation into CI pipeline

connect.yaml
Enabling assets as application type for the enabler
=> feat(connect): enabling assets application type for enabler

enabler/package-lock.json, enabler/package.json, processor/package-lock.json, processor/package.json
update package.json and package-lock.json
=> chore(all): update package version

processor/src/services/adyen-payment.service.ts
Fix bug for this ticket: https://commercetools.atlassian.net/browse/SCC-2237
=> fix(payments): fix bug while setting the payment methods for failure scenarios

enabler/package.json, processor/package.json
Update to v3.0.0
p.s. breaking change in `connect.yaml` is introduced in new version
=> chore(all): update version to v3.0.0

processor/src/services/abstract-payment.service.ts, processor/src/services/adyen-payment.service.ts, processor/test/services/adyen-payment.service.spec.ts
solved error processing the outcome of the payment modification against Adyen as it was setting the Failure state for the tx instead of the Pending one
=> fix(payment-modifications): fix payment modification result conversion to transaction state

README.md, connect.yaml
- reorder the modules to deploy enabler first
- add default value for commercetools env-var
- fix case sensitive issue
- update README.md
=> fix(all): fix connect.yaml

processor/package-lock.json, processor/package.json, processor/src/services/abstract-payment.service.ts, processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2273
=> feat(payments): removed validations for payments modifications

enabler/src/components/payment-methods/klarna-pay-later.ts, enabler/src/components/payment-methods/klarna-pay-now.ts, enabler/src/components/payment-methods/klarna-pay-over-time.ts
=> fix(klarna): force show pay button

README.md, docker-compose.yaml, enabler/dev-utils/session.js, enabler/index.html, processor/.env.template, processor/package.json
Ticket: https://commercetools.atlassian.net/browse/SCC-2367
Current dev tools for payment connectors has encountered some issue at the moment of integrating it with Checkout. We need to improve the testing tools to be able to reduce the risk of it not working on checkout after the development.
This PR implements a simple, but functional UI with the following; 
- Fields to select supported payment methods of the connector
- terms and condition checkbox
- Render the payment component when clicking on checkout, If the component has payment button then render only the PSP payment button, Otherwise render a custom button that executes the submit() on the payment component.
=> chore(processor): improve dev tools

enabler/dev-utils/session.js, enabler/src/payment-enabler/payment-enabler.ts, processor/src/services/converters/create-payment.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
@leungkinghin-ct @prateek-ct, as we would need to do deeper investigation on klarna, for the moment I have disables the klarna payment methods so that are not exposed in the merchant center. Once that is merged we can start with certification of apple pay and google pay of the version 4.1.0
=> chore(klarna): disable klarna for certification

enabler/dev-utils/session.js, processor/src/services/converters/create-payment.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
Reverts commercetools/connect-payment-integration-adyen#145
=> Revert "chore(klarna): disable klarna for certification"

enabler/dev-utils/session.js, enabler/src/components/payment-methods/klarna-pay-later.ts, enabler/src/components/payment-methods/klarna-pay-now.ts, enabler/src/components/payment-methods/klarna-pay-over-time.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/services/converters/helper.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts, processor/test/services/converters/helper.converter.spec.ts
changed Klarna payment method codes as per ticket: https://commercetools.atlassian.net/browse/SCC-2457
=> feat(klarna): changed klarna payment method codes to map to better codes

enabler/dev-utils/session.js, enabler/index.html, enabler/src/components/payment-methods/bancontactcard.ts, enabler/src/components/payment-methods/twint.ts, enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/config/payment-method.config.ts, processor/src/services/converters/helper.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
Add support for TWINT https://commercetools.atlassian.net/browse/SCC-2264
Add support for Bancontact card https://commercetools.atlassian.net/browse/SCC-2265
=> feat(payments): added support to TWINT and Bancontact cards

enabler/dev-utils/session.js, enabler/index.html, enabler/src/components/payment-methods/bancontactcard-mobile.ts, enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/config/payment-method.config.ts, processor/src/services/converters/helper.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
**Link to the ticket:** https://commercetools.atlassian.net/browse/SCC-2462
Adds support for Bancontact mobile.
=> feat(enabler/processor): add Bancontact Mobile support

processor/package.json, processor/src/services/converters/create-payment.converter.ts
More info: https://commercetools.atlassian.net/browse/SCC-2587
Adyen's required fields docs: https://docs.adyen.com/payment-methods/klarna/billie/#integration-requirements
=> feat(billie): populate Billie specific info when processing the payment

processor/src/services/adyen-payment.service.ts
added a userAction param to the return url to inform that the buyer cancelled the payment.
More info: https://commercetools.atlassian.net/browse/SCC-2586
=> feat(payments): added a userAction param to the payment return url 

processor/package-lock.json, processor/package.json, processor/src/libs/fastify/context/context.ts, processor/src/services/converters/create-payment.converter.ts, processor/src/services/converters/create-session.converter.ts
added support to send to Adyen the future order number if it is present in the session
https://commercetools.atlassian.net/browse/SCC-2635
=> feat(payments): added support to send to the future order number

processor/package-lock.json, processor/package.json, processor/src/libs/fastify/context/context.ts
Ticket info: https://commercetools.atlassian.net/browse/SCC-2810
=> chore(gc): update payment sdk

enabler/dev-utils/session.js, enabler/index.html, enabler/src/components/base.ts, enabler/src/components/payment-methods/blik.ts, enabler/src/dropin/dropin-embedded.ts, enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/config/payment-method.config.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2871
Support payments with Blik method
=> feat(payments): add support for Blik

enabler/dev-utils/session.js, enabler/index.html, enabler/src/components/payment-methods/przelewy24.ts, enabler/src/dropin/dropin-embedded.ts, enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/config/payment-method.config.ts, processor/src/services/converters/helper.converter.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2883
Added support for Przelewy24 payment method.
=> feat(payments): add support for Przelewy24

enabler/dev-utils/session.js, enabler/index.html, enabler/src/components/payment-methods/swish.ts, enabler/src/dropin/dropin-embedded.ts, enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts, processor/src/config/payment-method.config.ts, processor/src/services/converters/payment-components.converter.ts, processor/test/services/adyen-payment.service.spec.ts
https://commercetools.atlassian.net/browse/SCC-2870
=> feat(payments): add support for Swish

enabler/src/payment-enabler/adyen-payment-enabler.ts, enabler/src/payment-enabler/payment-enabler.ts
This will be used in SPA for improved error handling
Also added to onComplete in case it could be useful
=> feat(payments): Add method type to onError callback

enabler/package-lock.json, enabler/package.json
https://commercetools.atlassian.net/browse/SCC-3118
=> chore(dependencies): adyen-web upgrade to 6.11.0

processor/src/services/converters/create-payment.converter.ts
https://commercetools.atlassian.net/browse/SCC-3204
A customer has requested to send the line items information to Adyen for PayPal transactions.
=> feat(payments): send line items information for PayPal transactions

processor/src/libs/fastify/ip/ip.ts, processor/src/routes/adyen-payment.route.ts, processor/src/server/server.ts
https://commercetools.atlassian.net/browse/SCC-3175
=> feat(payments): add logic to retrieve the shopper IP and send it to Adyen

enabler/src/components/base.ts, enabler/src/components/payment-methods/bancontactcard-mobile.ts, enabler/src/components/payment-methods/bancontactcard.ts, enabler/src/components/payment-methods/blik.ts, enabler/src/components/payment-methods/card.ts, enabler/src/components/payment-methods/eps.ts, enabler/src/components/payment-methods/ideal.ts, enabler/src/components/payment-methods/mobilepay.ts, enabler/src/components/payment-methods/przelewy24.ts, enabler/src/components/payment-methods/sepadirectdebit.ts, enabler/src/components/payment-methods/swish.ts, enabler/src/components/payment-methods/twint.ts, enabler/src/components/payment-methods/vipps.ts, enabler/src/dropin/dropin-embedded.ts, enabler/src/payment-enabler/payment-enabler.ts
allow async mount and submit methods for PaymentComponent and DropinComponent interfaces.
=> updated the typings interface for DropIn and PaymentComponent

enabler/src/components/base.ts, enabler/src/components/payment-methods/afterpay.ts, enabler/src/components/payment-methods/bancontactcard-mobile.ts, enabler/src/components/payment-methods/bancontactcard.ts, enabler/src/components/payment-methods/blik.ts, enabler/src/components/payment-methods/card.ts, enabler/src/components/payment-methods/eps.ts, enabler/src/components/payment-methods/ideal.ts, enabler/src/components/payment-methods/mobilepay.ts, enabler/src/components/payment-methods/przelewy24.ts, enabler/src/components/payment-methods/sepadirectdebit.ts, enabler/src/components/payment-methods/swish.ts, enabler/src/components/payment-methods/twint.ts, enabler/src/components/payment-methods/vipps.ts, enabler/src/dropin/dropin-embedded.ts, enabler/src/payment-enabler/payment-enabler.ts
Revert the changed done in https://commercetools.atlassian.net/browse/SCC-3317
Commits Refs: d90abc7
=> revert: SCC-3317_support-async-mountings

enabler/jest.config.ts
- fix the unit test configuration for enabler
=> test(enabler): fix unit test
